// generated by genptr.py, do not modify
#include "g_ptrs.h"
extern int actor_move_attack;
extern int actor_move_death1;
extern int actor_move_death2;
extern int actor_move_flipoff;
extern int actor_move_pain1;
extern int actor_move_pain2;
extern int actor_move_pain3;
extern int actor_move_run;
extern int actor_move_stand;
extern int actor_move_taunt;
extern int actor_move_walk;
extern int arachnid_attack1;
extern int arachnid_attack_up1;
extern int arachnid_melee;
extern int arachnid_move_death;
extern int arachnid_move_pain1;
extern int arachnid_move_pain2;
extern int arachnid_move_run;
extern int arachnid_move_stand;
extern int arachnid_move_walk;
extern int berserk_move_attack_club;
extern int berserk_move_attack_slam;
extern int berserk_move_attack_spike;
extern int berserk_move_death1;
extern int berserk_move_death2;
extern int berserk_move_duck2;
extern int berserk_move_jump2;
extern int berserk_move_jump;
extern int berserk_move_jump_slam;
extern int berserk_move_pain1;
extern int berserk_move_pain2;
extern int berserk_move_run1;
extern int berserk_move_run_attack1;
extern int berserk_move_stand;
extern int berserk_move_stand_fidget;
extern int berserk_move_walk;
extern int boss2_move_attack_hb;
extern int boss2_move_attack_mg;
extern int boss2_move_attack_post_mg;
extern int boss2_move_attack_pre_mg;
extern int boss2_move_attack_rocket2;
extern int boss2_move_attack_rocket;
extern int boss2_move_death;
extern int boss2_move_pain_heavy;
extern int boss2_move_pain_light;
extern int boss2_move_run;
extern int boss2_move_stand;
extern int boss2_move_walk;
extern int brain_move_attack1;
extern int brain_move_attack2;
extern int brain_move_attack3;
extern int brain_move_attack4;
extern int brain_move_death1;
extern int brain_move_death2;
extern int brain_move_duck;
extern int brain_move_idle;
extern int brain_move_pain1;
extern int brain_move_pain2;
extern int brain_move_pain3;
extern int brain_move_run;
extern int brain_move_stand;
extern int brain_move_walk1;
extern int carrier_move_attack_gren;
extern int carrier_move_attack_mg;
extern int carrier_move_attack_post_gren;
extern int carrier_move_attack_post_mg;
extern int carrier_move_attack_pre_gren;
extern int carrier_move_attack_pre_mg;
extern int carrier_move_attack_rail;
extern int carrier_move_attack_rocket;
extern int carrier_move_death;
extern int carrier_move_pain_heavy;
extern int carrier_move_pain_light;
extern int carrier_move_run;
extern int carrier_move_spawn;
extern int carrier_move_stand;
extern int carrier_move_walk;
extern int chick_move_attack1;
extern int chick_move_death1;
extern int chick_move_death2;
extern int chick_move_duck;
extern int chick_move_end_attack1;
extern int chick_move_end_slash;
extern int chick_move_fidget;
extern int chick_move_pain1;
extern int chick_move_pain2;
extern int chick_move_pain3;
extern int chick_move_run;
extern int chick_move_slash;
extern int chick_move_stand;
extern int chick_move_start_attack1;
extern int chick_move_start_run;
extern int chick_move_start_slash;
extern int chick_move_walk;
extern int flipper_move_attack;
extern int flipper_move_death;
extern int flipper_move_pain1;
extern int flipper_move_pain2;
extern int flipper_move_run_loop;
extern int flipper_move_run_start;
extern int flipper_move_stand;
extern int flipper_move_start_run;
extern int flipper_move_walk;
extern int floater_move_attack1;
extern int floater_move_attack1a;
extern int floater_move_attack2;
extern int floater_move_attack3;
extern int floater_move_disguise;
extern int floater_move_pain1;
extern int floater_move_pain2;
extern int floater_move_pop;
extern int floater_move_run;
extern int floater_move_stand1;
extern int floater_move_stand2;
extern int floater_move_walk;
extern int flyer_move_attack2;
extern int flyer_move_attack3;
extern int flyer_move_end_melee;
extern int flyer_move_kamikaze;
extern int flyer_move_loop_melee;
extern int flyer_move_pain1;
extern int flyer_move_pain2;
extern int flyer_move_pain3;
extern int flyer_move_run;
extern int flyer_move_stand;
extern int flyer_move_start;
extern int flyer_move_start_melee;
extern int flyer_move_stop;
extern int flyer_move_walk;
extern int gekk_move_attack1;
extern int gekk_move_attack2;
extern int gekk_move_attack;
extern int gekk_move_chant;
extern int gekk_move_death1;
extern int gekk_move_death3;
extern int gekk_move_death4;
extern int gekk_move_idle2;
extern int gekk_move_idle;
extern int gekk_move_lduck;
extern int gekk_move_leapatk2;
extern int gekk_move_leapatk;
extern int gekk_move_pain1;
extern int gekk_move_pain2;
extern int gekk_move_pain;
extern int gekk_move_rduck;
extern int gekk_move_run;
extern int gekk_move_run_start;
extern int gekk_move_spit;
extern int gekk_move_stand;
extern int gekk_move_standunderwater;
extern int gekk_move_swim_loop;
extern int gekk_move_swim_start;
extern int gekk_move_walk;
extern int gekk_move_wdeath;
extern int gladb_move_attack_gun;
extern int gladiator_move_attack_gun;
extern int gladiator_move_attack_melee;
extern int gladiator_move_death;
extern int gladiator_move_pain;
extern int gladiator_move_pain_air;
extern int gladiator_move_run;
extern int gladiator_move_stand;
extern int gladiator_move_walk;
extern int guncmdr_move_attack_chain;
extern int guncmdr_move_attack_grenade_back;
extern int guncmdr_move_attack_grenade_back_dodge_left;
extern int guncmdr_move_attack_grenade_back_dodge_right;
extern int guncmdr_move_attack_kick;
extern int guncmdr_move_attack_mortar;
extern int guncmdr_move_attack_mortar_dodge;
extern int guncmdr_move_death1;
extern int guncmdr_move_death2;
extern int guncmdr_move_death3;
extern int guncmdr_move_death4;
extern int guncmdr_move_death5;
extern int guncmdr_move_death6;
extern int guncmdr_move_death7;
extern int guncmdr_move_duck_attack;
extern int guncmdr_move_endfire_chain;
extern int guncmdr_move_fidget;
extern int guncmdr_move_fire_chain;
extern int guncmdr_move_fire_chain_dodge_left;
extern int guncmdr_move_fire_chain_dodge_right;
extern int guncmdr_move_fire_chain_run;
extern int guncmdr_move_jump2;
extern int guncmdr_move_jump;
extern int guncmdr_move_pain1;
extern int guncmdr_move_pain2;
extern int guncmdr_move_pain3;
extern int guncmdr_move_pain4;
extern int guncmdr_move_pain5;
extern int guncmdr_move_pain6;
extern int guncmdr_move_pain7;
extern int guncmdr_move_run;
extern int guncmdr_move_stand;
extern int guncmdr_move_walk;
extern int gunner_move_attack_chain;
extern int gunner_move_attack_grenade2;
extern int gunner_move_attack_grenade;
extern int gunner_move_death;
extern int gunner_move_duck;
extern int gunner_move_endfire_chain;
extern int gunner_move_fidget;
extern int gunner_move_fire_chain;
extern int gunner_move_jump2;
extern int gunner_move_jump;
extern int gunner_move_pain1;
extern int gunner_move_pain2;
extern int gunner_move_pain3;
extern int gunner_move_run;
extern int gunner_move_runandshoot;
extern int gunner_move_stand;
extern int gunner_move_walk;
extern int hover_move_attack1;
extern int hover_move_attack2;
extern int hover_move_death1;
extern int hover_move_end_attack;
extern int hover_move_pain1;
extern int hover_move_pain2;
extern int hover_move_pain3;
extern int hover_move_run;
extern int hover_move_stand;
extern int hover_move_start_attack;
extern int hover_move_walk;
extern int infantry_move_attack1;
extern int infantry_move_attack1_classic;
extern int infantry_move_attack2;
extern int infantry_move_attack3;
extern int infantry_move_attack4;
extern int infantry_move_attack5;
extern int infantry_move_death1;
extern int infantry_move_death2;
extern int infantry_move_death3;
extern int infantry_move_duck;
extern int infantry_move_fidget;
extern int infantry_move_jump2;
extern int infantry_move_jump;
extern int infantry_move_pain1;
extern int infantry_move_pain2;
extern int infantry_move_run;
extern int infantry_move_stand;
extern int infantry_move_walk;
extern int insane_move_crawl;
extern int insane_move_crawl_death;
extern int insane_move_crawl_pain;
extern int insane_move_cross;
extern int insane_move_down;
extern int insane_move_downtoup;
extern int insane_move_jumpdown;
extern int insane_move_run_insane;
extern int insane_move_run_normal;
extern int insane_move_runcrawl;
extern int insane_move_stand_death;
extern int insane_move_stand_insane;
extern int insane_move_stand_normal;
extern int insane_move_stand_pain;
extern int insane_move_struggle_cross;
extern int insane_move_uptodown;
extern int insane_move_walk_insane;
extern int insane_move_walk_normal;
extern int jorg_move_attack1;
extern int jorg_move_attack2;
extern int jorg_move_death;
extern int jorg_move_end_attack1;
extern int jorg_move_pain1;
extern int jorg_move_pain2;
extern int jorg_move_pain3;
extern int jorg_move_run;
extern int jorg_move_stand;
extern int jorg_move_start_attack1;
extern int jorg_move_walk;
extern int makron_move_attack3;
extern int makron_move_attack4;
extern int makron_move_attack5;
extern int makron_move_death2;
extern int makron_move_pain4;
extern int makron_move_pain5;
extern int makron_move_pain6;
extern int makron_move_run;
extern int makron_move_sight;
extern int makron_move_stand;
extern int makron_move_walk;
extern int medic_move_attackBlaster;
extern int medic_move_attackCable;
extern int medic_move_attackHyperBlaster;
extern int medic_move_callReinforcements;
extern int medic_move_death;
extern int medic_move_duck;
extern int medic_move_pain1;
extern int medic_move_pain2;
extern int medic_move_run;
extern int medic_move_stand;
extern int medic_move_walk;
extern int mutant_move_attack;
extern int mutant_move_death1;
extern int mutant_move_death2;
extern int mutant_move_idle;
extern int mutant_move_jump;
extern int mutant_move_jump_down;
extern int mutant_move_jump_up;
extern int mutant_move_pain1;
extern int mutant_move_pain2;
extern int mutant_move_pain3;
extern int mutant_move_run;
extern int mutant_move_stand;
extern int mutant_move_start_walk;
extern int mutant_move_walk;
extern int parasite_move_break;
extern int parasite_move_death;
extern int parasite_move_drain;
extern int parasite_move_end_fidget;
extern int parasite_move_fidget;
extern int parasite_move_fire_proboscis;
extern int parasite_move_jump_down;
extern int parasite_move_jump_up;
extern int parasite_move_pain1;
extern int parasite_move_run;
extern int parasite_move_stand;
extern int parasite_move_start_fidget;
extern int parasite_move_start_run;
extern int parasite_move_start_walk;
extern int parasite_move_walk;
extern int shambler_attack_magic;
extern int shambler_attack_smash;
extern int shambler_attack_swingl;
extern int shambler_attack_swingr;
extern int shambler_move_death;
extern int shambler_move_pain;
extern int shambler_move_run;
extern int shambler_move_stand;
extern int shambler_move_walk;
extern int soldier_move_attack1;
extern int soldier_move_attack2;
extern int soldier_move_attack3;
extern int soldier_move_attack4;
extern int soldier_move_attack5;
extern int soldier_move_attack6;
extern int soldier_move_blind;
extern int soldier_move_death1;
extern int soldier_move_death2;
extern int soldier_move_death3;
extern int soldier_move_death4;
extern int soldier_move_death5;
extern int soldier_move_death6;
extern int soldier_move_duck;
extern int soldier_move_pain1;
extern int soldier_move_pain2;
extern int soldier_move_pain3;
extern int soldier_move_pain4;
extern int soldier_move_run;
extern int soldier_move_stand1;
extern int soldier_move_stand2;
extern int soldier_move_stand3;
extern int soldier_move_start_run;
extern int soldier_move_trip;
extern int soldier_move_walk1;
extern int soldier_move_walk2;
extern int soldierh_move_attack1;
extern int soldierh_move_attack2;
extern int stalker_move_death;
extern int stalker_move_false_death;
extern int stalker_move_false_death_end;
extern int stalker_move_false_death_start;
extern int stalker_move_idle2;
extern int stalker_move_idle;
extern int stalker_move_jump_down;
extern int stalker_move_jump_straightup;
extern int stalker_move_jump_up;
extern int stalker_move_pain;
extern int stalker_move_run;
extern int stalker_move_shoot;
extern int stalker_move_stand;
extern int stalker_move_swing_l;
extern int stalker_move_swing_r;
extern int stalker_move_walk;
extern int supertank_move_attack1;
extern int supertank_move_attack2;
extern int supertank_move_death;
extern int supertank_move_end_attack1;
extern int supertank_move_forward;
extern int supertank_move_pain1;
extern int supertank_move_pain2;
extern int supertank_move_pain3;
extern int supertank_move_run;
extern int supertank_move_stand;
extern int tank_move_attack_blast;
extern int tank_move_attack_chain;
extern int tank_move_attack_fire_rocket;
extern int tank_move_attack_post_blast;
extern int tank_move_attack_post_rocket;
extern int tank_move_attack_pre_rocket;
extern int tank_move_attack_strike;
extern int tank_move_death;
extern int tank_move_pain1;
extern int tank_move_pain2;
extern int tank_move_pain3;
extern int tank_move_reattack_blast;
extern int tank_move_run;
extern int tank_move_stand;
extern int tank_move_start_run;
extern int tank_move_walk;
extern int turret_move_fire;
extern int turret_move_ready_gun;
extern int turret_move_run;
extern int turret_move_seek;
extern int turret_move_stand;
extern void actor_attack(void);
extern void actor_die(void);
extern void actor_pain(void);
extern void actor_run(void);
extern void actor_stand(void);
extern void actor_use(void);
extern void actor_walk(void);
extern void AngleMove_Begin(void);
extern void AngleMove_Done(void);
extern void AngleMove_Final(void);
extern void arachnid_attack(void);
extern void arachnid_die(void);
extern void arachnid_pain(void);
extern void arachnid_run(void);
extern void arachnid_sight(void);
extern void arachnid_stand(void);
extern void arachnid_walk(void);
extern void barrel_burn(void);
extern void barrel_delay(void);
extern void barrel_explode(void);
extern void barrel_start(void);
extern void barrel_think(void);
extern void barrel_touch(void);
extern void berserk_attack(void);
extern void berserk_blocked(void);
extern void berserk_die(void);
extern void berserk_jump_touch(void);
extern void berserk_melee(void);
extern void berserk_pain(void);
extern void berserk_run(void);
extern void berserk_search(void);
extern void berserk_sight(void);
extern void berserk_stand(void);
extern void berserk_walk(void);
extern void bfg_explode(void);
extern void bfg_think(void);
extern void bfg_touch(void);
extern void blaster2_touch(void);
extern void blaster_touch(void);
extern void body_die(void);
extern void boss2_attack(void);
extern void Boss2_CheckAttack(void);
extern void boss2_die(void);
extern void boss2_pain(void);
extern void boss2_run(void);
extern void boss2_search(void);
extern void boss2_stand(void);
extern void boss2_walk(void);
extern void BossExplode(void);
extern void brain_attack(void);
extern void brain_die(void);
extern void brain_idle(void);
extern void brain_melee(void);
extern void brain_pain(void);
extern void brain_run(void);
extern void brain_search(void);
extern void brain_sight(void);
extern void brain_stand(void);
extern void brain_walk(void);
extern void button_done(void);
extern void button_killed(void);
extern void button_return(void);
extern void button_touch(void);
extern void button_use(void);
extern void button_wait(void);
extern void carrier_attack(void);
extern void Carrier_CheckAttack(void);
extern void carrier_die(void);
extern void carrier_pain(void);
extern void carrier_run(void);
extern void carrier_sight(void);
extern void carrier_stand(void);
extern void carrier_walk(void);
extern void chick_attack(void);
extern void chick_die(void);
extern void chick_melee(void);
extern void chick_pain(void);
extern void chick_run(void);
extern void chick_sight(void);
extern void chick_stand(void);
extern void chick_walk(void);
extern void commander_body_drop(void);
extern void commander_body_think(void);
extern void commander_body_use(void);
extern void dabeam_hit(void);
extern void debris_die(void);
extern void door_blocked(void);
extern void door_go_down(void);
extern void door_hit_bottom(void);
extern void door_hit_top(void);
extern void door_killed(void);
extern void door_secret_blocked(void);
extern void door_secret_die(void);
extern void door_secret_done(void);
extern void door_secret_move1(void);
extern void door_secret_move2(void);
extern void door_secret_move3(void);
extern void door_secret_move4(void);
extern void door_secret_move5(void);
extern void door_secret_move6(void);
extern void door_secret_use(void);
extern void door_touch(void);
extern void door_use(void);
extern void DoRespawn(void);
extern void drop_make_touchable(void);
extern void drop_temp_touch(void);
extern void droppod_light_think(void);
extern void droptofloor(void);
extern void flare_think(void);
extern void flare_touch(void);
extern void flechette_touch(void);
extern void flipper_die(void);
extern void flipper_melee(void);
extern void flipper_pain(void);
extern void flipper_sight(void);
extern void flipper_stand(void);
extern void flipper_start_run(void);
extern void flipper_walk(void);
extern void floater_attack(void);
extern void floater_die(void);
extern void floater_idle(void);
extern void floater_melee(void);
extern void floater_pain(void);
extern void floater_run(void);
extern void floater_sight(void);
extern void floater_stand(void);
extern void floater_walk(void);
extern void flyer_attack(void);
extern void flyer_die(void);
extern void flyer_idle(void);
extern void flyer_melee(void);
extern void flyer_pain(void);
extern void flyer_run(void);
extern void flyer_sight(void);
extern void flyer_stand(void);
extern void flyer_walk(void);
extern void flymonster_start_go(void);
extern void func_clock_think(void);
extern void func_clock_use(void);
extern void func_conveyor_use(void);
extern void func_explosive_explode(void);
extern void func_explosive_spawn(void);
extern void func_explosive_use(void);
extern void func_eye_setup(void);
extern void func_eye_think(void);
extern void func_object_release(void);
extern void func_object_touch(void);
extern void func_object_use(void);
extern void func_timer_think(void);
extern void func_timer_use(void);
extern void func_train_find(void);
extern void func_wall_use(void);
extern void G_FreeEdict(void);
extern void gekk_attack(void);
extern void gekk_checkattack(void);
extern void gekk_die(void);
extern void gekk_dodge(void);
extern void gekk_idle(void);
extern void gekk_jump_touch(void);
extern void gekk_melee(void);
extern void gekk_pain(void);
extern void gekk_run_start(void);
extern void gekk_search(void);
extern void gekk_sight(void);
extern void gekk_stand(void);
extern void gekk_walk(void);
extern void gib_die(void);
extern void gib_think(void);
extern void gib_touch(void);
extern void gladiator_attack(void);
extern void gladiator_die(void);
extern void gladiator_idle(void);
extern void gladiator_melee(void);
extern void gladiator_pain(void);
extern void gladiator_run(void);
extern void gladiator_search(void);
extern void gladiator_sight(void);
extern void gladiator_stand(void);
extern void gladiator_walk(void);
extern void Grenade_Explode(void);
extern void Grenade_Touch(void);
extern void guncmdr_attack(void);
extern void guncmdr_blocked(void);
extern void guncmdr_die(void);
extern void guncmdr_pain(void);
extern void guncmdr_run(void);
extern void guncmdr_search(void);
extern void guncmdr_sight(void);
extern void guncmdr_stand(void);
extern void guncmdr_walk(void);
extern void gunner_attack(void);
extern void gunner_blocked(void);
extern void gunner_die(void);
extern void gunner_pain(void);
extern void gunner_run(void);
extern void gunner_search(void);
extern void gunner_sight(void);
extern void gunner_stand(void);
extern void gunner_walk(void);
extern void heat_think(void);
extern void hover_deadthink(void);
extern void hover_die(void);
extern void hover_pain(void);
extern void hover_run(void);
extern void hover_search(void);
extern void hover_sight(void);
extern void hover_stand(void);
extern void hover_start_attack(void);
extern void hover_walk(void);
extern void hurt_touch(void);
extern void hurt_use(void);
extern void hyper_blaster_touch(void);
extern void infantry_attack(void);
extern void infantry_blocked(void);
extern void infantry_die(void);
extern void infantry_fidget(void);
extern void infantry_pain(void);
extern void infantry_run(void);
extern void infantry_sight(void);
extern void infantry_stand(void);
extern void infantry_walk(void);
extern void insane_die(void);
extern void insane_pain(void);
extern void insane_run(void);
extern void insane_stand(void);
extern void insane_walk(void);
extern void ionripper_sparks(void);
extern void ionripper_touch(void);
extern void jorg_attack(void);
extern void Jorg_CheckAttack(void);
extern void jorg_die(void);
extern void jorg_pain(void);
extern void jorg_run(void);
extern void jorg_search(void);
extern void jorg_stand(void);
extern void jorg_walk(void);
extern void lavaball_fly(void);
extern void lavaball_touch(void);
extern void light_use(void);
extern void loogie_touch(void);
extern void M_CheckAttack(void);
extern void M_droptofloor(void);
extern void M_FliesOff(void);
extern void M_FliesOn(void);
extern void M_MonsterDodge(void);
extern void makron_attack(void);
extern void Makron_CheckAttack(void);
extern void makron_die(void);
extern void makron_pain(void);
extern void makron_run(void);
extern void makron_sight(void);
extern void makron_stand(void);
extern void makron_torso_think(void);
extern void makron_walk(void);
extern void MakronSpawn(void);
extern void medic_attack(void);
extern void medic_checkattack(void);
extern void medic_die(void);
extern void medic_idle(void);
extern void medic_pain(void);
extern void medic_run(void);
extern void medic_search(void);
extern void medic_sight(void);
extern void medic_stand(void);
extern void medic_walk(void);
extern void MegaHealth_think(void);
extern void misc_banner_think(void);
extern void misc_blackhole_think(void);
extern void misc_blackhole_use(void);
extern void misc_deadsoldier_die(void);
extern void misc_easterchick2_think(void);
extern void misc_easterchick_think(void);
extern void misc_eastertank_think(void);
extern void misc_flare_use(void);
extern void misc_nuke_use(void);
extern void misc_satellite_dish_think(void);
extern void misc_satellite_dish_use(void);
extern void misc_strogg_ship_use(void);
extern void misc_viper_bomb_prethink(void);
extern void misc_viper_bomb_touch(void);
extern void misc_viper_bomb_use(void);
extern void misc_viper_missile_use(void);
extern void misc_viper_use(void);
extern void monster_think(void);
extern void monster_triggered_spawn(void);
extern void monster_triggered_spawn_use(void);
extern void monster_use(void);
extern void Move_Begin(void);
extern void Move_Done(void);
extern void Move_Final(void);
extern void multi_wait(void);
extern void mutant_blocked(void);
extern void mutant_checkattack(void);
extern void mutant_die(void);
extern void mutant_idle(void);
extern void mutant_jump(void);
extern void mutant_jump_touch(void);
extern void mutant_melee(void);
extern void mutant_pain(void);
extern void mutant_run(void);
extern void mutant_search(void);
extern void mutant_sight(void);
extern void mutant_stand(void);
extern void mutant_walk(void);
extern void parasite_attack(void);
extern void parasite_blocked(void);
extern void parasite_die(void);
extern void parasite_idle(void);
extern void parasite_pain(void);
extern void parasite_sight(void);
extern void parasite_stand(void);
extern void parasite_start_run(void);
extern void parasite_start_walk(void);
extern void path_corner_touch(void);
extern void plasma_touch(void);
extern void plat2_activate(void);
extern void plat2_blocked(void);
extern void plat2_go_down(void);
extern void plat2_go_up(void);
extern void plat2_hit_bottom(void);
extern void plat2_hit_top(void);
extern void plat_blocked(void);
extern void plat_go_down(void);
extern void plat_hit_bottom(void);
extern void plat_hit_top(void);
extern void player_die(void);
extern void player_pain(void);
extern void point_combat_touch(void);
extern void proboscis_die(void);
extern void proboscis_reset(void);
extern void proboscis_think(void);
extern void proboscis_touch(void);
extern void rocket_touch(void);
extern void rotating_blocked(void);
extern void rotating_light_alarm(void);
extern void rotating_light_killed(void);
extern void rotating_light_use(void);
extern void rotating_touch(void);
extern void rotating_use(void);
extern void shambler_attack(void);
extern void shambler_die(void);
extern void shambler_idle(void);
extern void shambler_melee(void);
extern void shambler_pain(void);
extern void shambler_run(void);
extern void shambler_sight(void);
extern void shambler_stand(void);
extern void shambler_walk(void);
extern void smart_water_blocked(void);
extern void smart_water_go_up(void);
extern void soldier_attack(void);
extern void soldier_blind(void);
extern void soldier_die(void);
extern void soldier_pain(void);
extern void soldier_run(void);
extern void soldier_sight(void);
extern void soldier_stand(void);
extern void soldier_walk(void);
extern void SP_CreateCoopSpots(void);
extern void SP_FixCoopSpots(void);
extern void spawngrow_think(void);
extern void stalker_attack_melee(void);
extern void stalker_attack_ranged(void);
extern void stalker_die(void);
extern void stalker_dodge(void);
extern void stalker_idle(void);
extern void stalker_pain(void);
extern void stalker_run(void);
extern void stalker_sight(void);
extern void stalker_stand(void);
extern void stalker_walk(void);
extern void stationarymonster_start_go(void);
extern void stationarymonster_triggered_spawn(void);
extern void stationarymonster_triggered_spawn_use(void);
extern void supertank_attack(void);
extern void supertank_die(void);
extern void supertank_pain(void);
extern void supertank_run(void);
extern void supertank_search(void);
extern void supertank_stand(void);
extern void supertank_walk(void);
extern void swimmonster_start_go(void);
extern void tank_attack(void);
extern void tank_die(void);
extern void tank_idle(void);
extern void tank_pain(void);
extern void tank_run(void);
extern void tank_sight(void);
extern void tank_stand(void);
extern void tank_walk(void);
extern void target_actor_touch(void);
extern void target_anger_use(void);
extern void target_crosslevel_target_think(void);
extern void target_crossunit_target_think(void);
extern void target_earthquake_think(void);
extern void target_earthquake_use(void);
extern void target_explosion_explode(void);
extern void target_laser_start(void);
extern void target_laser_think(void);
extern void target_laser_use(void);
extern void target_light_flicker_think(void);
extern void target_light_use(void);
extern void target_lightramp_think(void);
extern void target_lightramp_use(void);
extern void target_poi_setup(void);
extern void target_poi_use(void);
extern void target_steam_start(void);
extern void target_string_use(void);
extern void teleporter_touch(void);
extern void tesla_activate(void);
extern void tesla_die(void);
extern void tesla_lava(void);
extern void tesla_think(void);
extern void tesla_think_active(void);
extern void tesla_zap(void);
extern void TH_viewthing(void);
extern void Think_AccelMove(void);
extern void Think_Boss3Stand(void);
extern void Think_CalcMoveSpeed(void);
extern void Think_Delay(void);
extern void Think_SpawnDoorTrigger(void);
extern void Touch_DoorTrigger(void);
extern void Touch_Item(void);
extern void Touch_Multi(void);
extern void Touch_Plat_Center(void);
extern void Touch_Plat_Center2(void);
extern void tracker_fly(void);
extern void tracker_pain_daemon_think(void);
extern void tracker_touch(void);
extern void train_blocked(void);
extern void train_next(void);
extern void train_use(void);
extern void train_wait(void);
extern void Trap_Think(void);
extern void trigger_counter_use(void);
extern void trigger_crosslevel_trigger_use(void);
extern void trigger_crossunit_trigger_use(void);
extern void trigger_elevator_init(void);
extern void trigger_elevator_use(void);
extern void trigger_enable(void);
extern void trigger_flashlight_touch(void);
extern void trigger_gravity_touch(void);
extern void trigger_health_relay_use(void);
extern void trigger_key_use(void);
extern void trigger_monsterjump_touch(void);
extern void trigger_push_touch(void);
extern void trigger_relay_use(void);
extern void trigger_teleport_touch(void);
extern void trigger_teleport_use(void);
extern void turret_activate(void);
extern void turret_attack(void);
extern void turret_blocked(void);
extern void turret_breach_finish_init(void);
extern void turret_breach_think(void);
extern void turret_checkattack(void);
extern void turret_die(void);
extern void turret_driver_die(void);
extern void turret_driver_link(void);
extern void turret_driver_think(void);
extern void turret_pain(void);
extern void turret_run(void);
extern void turret_search(void);
extern void turret_sight(void);
extern void turret_stand(void);
extern void turret_wake(void);
extern void turret_walk(void);
extern void Use_Areaportal(void);
extern void Use_Boss3(void);
extern void Use_Item(void);
extern void use_killbox(void);
extern void Use_Multi(void);
extern void Use_Plat(void);
extern void Use_Plat2(void);
extern void use_target_autosave(void);
extern void use_target_blaster(void);
extern void use_target_changelevel(void);
extern void use_target_explosion(void);
extern void use_target_goal(void);
extern void Use_Target_Help(void);
extern void use_target_music(void);
extern void use_target_secret(void);
extern void use_target_sky(void);
extern void use_target_spawner(void);
extern void Use_Target_Speaker(void);
extern void use_target_splash(void);
extern void use_target_steam(void);
extern void use_target_story(void);
extern void Use_Target_Tent(void);
extern void walkmonster_start_go(void);
const save_ptr_t save_ptrs[] = {
{ P_prethink, misc_viper_bomb_prethink },
{ P_think, AngleMove_Begin },
{ P_think, AngleMove_Done },
{ P_think, AngleMove_Final },
{ P_think, barrel_burn },
{ P_think, barrel_explode },
{ P_think, barrel_start },
{ P_think, barrel_think },
{ P_think, bfg_explode },
{ P_think, bfg_think },
{ P_think, BossExplode },
{ P_think, button_return },
{ P_think, commander_body_drop },
{ P_think, commander_body_think },
{ P_think, dabeam_hit },
{ P_think, door_go_down },
{ P_think, door_secret_move2 },
{ P_think, door_secret_move4 },
{ P_think, door_secret_move6 },
{ P_think, DoRespawn },
{ P_think, drop_make_touchable },
{ P_think, droppod_light_think },
{ P_think, droptofloor },
{ P_think, flare_think },
{ P_think, flymonster_start_go },
{ P_think, func_clock_think },
{ P_think, func_eye_setup },
{ P_think, func_eye_think },
{ P_think, func_object_release },
{ P_think, func_timer_think },
{ P_think, func_train_find },
{ P_think, G_FreeEdict },
{ P_think, gib_think },
{ P_think, Grenade_Explode },
{ P_think, heat_think },
{ P_think, hover_deadthink },
{ P_think, ionripper_sparks },
{ P_think, lavaball_fly },
{ P_think, M_droptofloor },
{ P_think, M_FliesOff },
{ P_think, M_FliesOn },
{ P_think, makron_torso_think },
{ P_think, MakronSpawn },
{ P_think, MegaHealth_think },
{ P_think, misc_banner_think },
{ P_think, misc_blackhole_think },
{ P_think, misc_easterchick2_think },
{ P_think, misc_easterchick_think },
{ P_think, misc_eastertank_think },
{ P_think, misc_satellite_dish_think },
{ P_think, monster_think },
{ P_think, monster_triggered_spawn },
{ P_think, Move_Begin },
{ P_think, Move_Done },
{ P_think, Move_Final },
{ P_think, multi_wait },
{ P_think, plat2_go_down },
{ P_think, plat2_go_up },
{ P_think, plat_go_down },
{ P_think, proboscis_reset },
{ P_think, proboscis_think },
{ P_think, rotating_light_alarm },
{ P_think, smart_water_go_up },
{ P_think, SP_CreateCoopSpots },
{ P_think, SP_FixCoopSpots },
{ P_think, spawngrow_think },
{ P_think, stationarymonster_start_go },
{ P_think, stationarymonster_triggered_spawn },
{ P_think, swimmonster_start_go },
{ P_think, target_crosslevel_target_think },
{ P_think, target_crossunit_target_think },
{ P_think, target_earthquake_think },
{ P_think, target_explosion_explode },
{ P_think, target_laser_start },
{ P_think, target_laser_think },
{ P_think, target_light_flicker_think },
{ P_think, target_lightramp_think },
{ P_think, target_poi_setup },
{ P_think, target_steam_start },
{ P_think, tesla_activate },
{ P_think, tesla_think },
{ P_think, tesla_think_active },
{ P_think, TH_viewthing },
{ P_think, Think_AccelMove },
{ P_think, Think_Boss3Stand },
{ P_think, Think_CalcMoveSpeed },
{ P_think, Think_Delay },
{ P_think, Think_SpawnDoorTrigger },
{ P_think, tracker_fly },
{ P_think, tracker_pain_daemon_think },
{ P_think, train_next },
{ P_think, Trap_Think },
{ P_think, trigger_elevator_init },
{ P_think, turret_breach_finish_init },
{ P_think, turret_breach_think },
{ P_think, turret_driver_link },
{ P_think, turret_driver_think },
{ P_think, walkmonster_start_go },
{ P_blocked, door_blocked },
{ P_blocked, door_secret_blocked },
{ P_blocked, plat2_blocked },
{ P_blocked, plat_blocked },
{ P_blocked, rotating_blocked },
{ P_blocked, smart_water_blocked },
{ P_blocked, train_blocked },
{ P_blocked, turret_blocked },
{ P_touch, barrel_touch },
{ P_touch, berserk_jump_touch },
{ P_touch, bfg_touch },
{ P_touch, blaster2_touch },
{ P_touch, blaster_touch },
{ P_touch, button_touch },
{ P_touch, door_touch },
{ P_touch, drop_temp_touch },
{ P_touch, flare_touch },
{ P_touch, flechette_touch },
{ P_touch, func_object_touch },
{ P_touch, gekk_jump_touch },
{ P_touch, gib_touch },
{ P_touch, Grenade_Touch },
{ P_touch, hurt_touch },
{ P_touch, hyper_blaster_touch },
{ P_touch, ionripper_touch },
{ P_touch, lavaball_touch },
{ P_touch, loogie_touch },
{ P_touch, misc_viper_bomb_touch },
{ P_touch, mutant_jump_touch },
{ P_touch, path_corner_touch },
{ P_touch, plasma_touch },
{ P_touch, point_combat_touch },
{ P_touch, proboscis_touch },
{ P_touch, rocket_touch },
{ P_touch, rotating_touch },
{ P_touch, target_actor_touch },
{ P_touch, teleporter_touch },
{ P_touch, tesla_lava },
{ P_touch, tesla_zap },
{ P_touch, Touch_DoorTrigger },
{ P_touch, Touch_Item },
{ P_touch, Touch_Multi },
{ P_touch, Touch_Plat_Center },
{ P_touch, Touch_Plat_Center2 },
{ P_touch, tracker_touch },
{ P_touch, trigger_flashlight_touch },
{ P_touch, trigger_gravity_touch },
{ P_touch, trigger_monsterjump_touch },
{ P_touch, trigger_push_touch },
{ P_touch, trigger_teleport_touch },
{ P_use, actor_use },
{ P_use, button_use },
{ P_use, commander_body_use },
{ P_use, door_secret_use },
{ P_use, door_use },
{ P_use, func_clock_use },
{ P_use, func_conveyor_use },
{ P_use, func_explosive_spawn },
{ P_use, func_explosive_use },
{ P_use, func_object_use },
{ P_use, func_timer_use },
{ P_use, func_wall_use },
{ P_use, hurt_use },
{ P_use, light_use },
{ P_use, misc_blackhole_use },
{ P_use, misc_flare_use },
{ P_use, misc_nuke_use },
{ P_use, misc_satellite_dish_use },
{ P_use, misc_strogg_ship_use },
{ P_use, misc_viper_bomb_use },
{ P_use, misc_viper_missile_use },
{ P_use, misc_viper_use },
{ P_use, monster_triggered_spawn_use },
{ P_use, monster_use },
{ P_use, plat2_activate },
{ P_use, rotating_light_use },
{ P_use, rotating_use },
{ P_use, stationarymonster_triggered_spawn_use },
{ P_use, target_anger_use },
{ P_use, target_earthquake_use },
{ P_use, target_laser_use },
{ P_use, target_light_use },
{ P_use, target_lightramp_use },
{ P_use, target_poi_use },
{ P_use, target_string_use },
{ P_use, train_use },
{ P_use, trigger_counter_use },
{ P_use, trigger_crosslevel_trigger_use },
{ P_use, trigger_crossunit_trigger_use },
{ P_use, trigger_elevator_use },
{ P_use, trigger_enable },
{ P_use, trigger_health_relay_use },
{ P_use, trigger_key_use },
{ P_use, trigger_relay_use },
{ P_use, trigger_teleport_use },
{ P_use, turret_activate },
{ P_use, Use_Areaportal },
{ P_use, Use_Boss3 },
{ P_use, Use_Item },
{ P_use, use_killbox },
{ P_use, Use_Multi },
{ P_use, Use_Plat },
{ P_use, Use_Plat2 },
{ P_use, use_target_autosave },
{ P_use, use_target_blaster },
{ P_use, use_target_changelevel },
{ P_use, use_target_explosion },
{ P_use, use_target_goal },
{ P_use, Use_Target_Help },
{ P_use, use_target_music },
{ P_use, use_target_secret },
{ P_use, use_target_sky },
{ P_use, use_target_spawner },
{ P_use, Use_Target_Speaker },
{ P_use, use_target_splash },
{ P_use, use_target_steam },
{ P_use, use_target_story },
{ P_use, Use_Target_Tent },
{ P_pain, actor_pain },
{ P_pain, arachnid_pain },
{ P_pain, berserk_pain },
{ P_pain, boss2_pain },
{ P_pain, brain_pain },
{ P_pain, carrier_pain },
{ P_pain, chick_pain },
{ P_pain, flipper_pain },
{ P_pain, floater_pain },
{ P_pain, flyer_pain },
{ P_pain, gekk_pain },
{ P_pain, gladiator_pain },
{ P_pain, guncmdr_pain },
{ P_pain, gunner_pain },
{ P_pain, hover_pain },
{ P_pain, infantry_pain },
{ P_pain, insane_pain },
{ P_pain, jorg_pain },
{ P_pain, makron_pain },
{ P_pain, medic_pain },
{ P_pain, mutant_pain },
{ P_pain, parasite_pain },
{ P_pain, player_pain },
{ P_pain, shambler_pain },
{ P_pain, soldier_pain },
{ P_pain, stalker_pain },
{ P_pain, supertank_pain },
{ P_pain, tank_pain },
{ P_pain, turret_pain },
{ P_die, actor_die },
{ P_die, arachnid_die },
{ P_die, barrel_delay },
{ P_die, berserk_die },
{ P_die, body_die },
{ P_die, boss2_die },
{ P_die, brain_die },
{ P_die, button_killed },
{ P_die, carrier_die },
{ P_die, chick_die },
{ P_die, debris_die },
{ P_die, door_killed },
{ P_die, door_secret_die },
{ P_die, flipper_die },
{ P_die, floater_die },
{ P_die, flyer_die },
{ P_die, func_explosive_explode },
{ P_die, gekk_die },
{ P_die, gib_die },
{ P_die, gladiator_die },
{ P_die, guncmdr_die },
{ P_die, gunner_die },
{ P_die, hover_die },
{ P_die, infantry_die },
{ P_die, insane_die },
{ P_die, jorg_die },
{ P_die, makron_die },
{ P_die, medic_die },
{ P_die, misc_deadsoldier_die },
{ P_die, mutant_die },
{ P_die, parasite_die },
{ P_die, player_die },
{ P_die, proboscis_die },
{ P_die, rotating_light_killed },
{ P_die, shambler_die },
{ P_die, soldier_die },
{ P_die, stalker_die },
{ P_die, supertank_die },
{ P_die, tank_die },
{ P_die, tesla_die },
{ P_die, turret_die },
{ P_die, turret_driver_die },
{ P_moveinfo_endfunc, button_done },
{ P_moveinfo_endfunc, button_wait },
{ P_moveinfo_endfunc, door_hit_bottom },
{ P_moveinfo_endfunc, door_hit_top },
{ P_moveinfo_endfunc, door_secret_done },
{ P_moveinfo_endfunc, door_secret_move1 },
{ P_moveinfo_endfunc, door_secret_move3 },
{ P_moveinfo_endfunc, door_secret_move5 },
{ P_moveinfo_endfunc, plat2_hit_bottom },
{ P_moveinfo_endfunc, plat2_hit_top },
{ P_moveinfo_endfunc, plat_hit_bottom },
{ P_moveinfo_endfunc, plat_hit_top },
{ P_moveinfo_endfunc, train_wait },
{ P_moveinfo_endfunc, turret_wake },
{ P_monsterinfo_currentmove, &actor_move_attack },
{ P_monsterinfo_currentmove, &actor_move_death1 },
{ P_monsterinfo_currentmove, &actor_move_death2 },
{ P_monsterinfo_currentmove, &actor_move_flipoff },
{ P_monsterinfo_currentmove, &actor_move_pain1 },
{ P_monsterinfo_currentmove, &actor_move_pain2 },
{ P_monsterinfo_currentmove, &actor_move_pain3 },
{ P_monsterinfo_currentmove, &actor_move_run },
{ P_monsterinfo_currentmove, &actor_move_stand },
{ P_monsterinfo_currentmove, &actor_move_taunt },
{ P_monsterinfo_currentmove, &actor_move_walk },
{ P_monsterinfo_currentmove, &arachnid_attack1 },
{ P_monsterinfo_currentmove, &arachnid_attack_up1 },
{ P_monsterinfo_currentmove, &arachnid_melee },
{ P_monsterinfo_currentmove, &arachnid_move_death },
{ P_monsterinfo_currentmove, &arachnid_move_pain1 },
{ P_monsterinfo_currentmove, &arachnid_move_pain2 },
{ P_monsterinfo_currentmove, &arachnid_move_run },
{ P_monsterinfo_currentmove, &arachnid_move_stand },
{ P_monsterinfo_currentmove, &arachnid_move_walk },
{ P_monsterinfo_currentmove, &berserk_move_attack_club },
{ P_monsterinfo_currentmove, &berserk_move_attack_slam },
{ P_monsterinfo_currentmove, &berserk_move_attack_spike },
{ P_monsterinfo_currentmove, &berserk_move_death1 },
{ P_monsterinfo_currentmove, &berserk_move_death2 },
{ P_monsterinfo_currentmove, &berserk_move_duck2 },
{ P_monsterinfo_currentmove, &berserk_move_jump },
{ P_monsterinfo_currentmove, &berserk_move_jump2 },
{ P_monsterinfo_currentmove, &berserk_move_jump_slam },
{ P_monsterinfo_currentmove, &berserk_move_pain1 },
{ P_monsterinfo_currentmove, &berserk_move_pain2 },
{ P_monsterinfo_currentmove, &berserk_move_run1 },
{ P_monsterinfo_currentmove, &berserk_move_run_attack1 },
{ P_monsterinfo_currentmove, &berserk_move_stand },
{ P_monsterinfo_currentmove, &berserk_move_stand_fidget },
{ P_monsterinfo_currentmove, &berserk_move_walk },
{ P_monsterinfo_currentmove, &boss2_move_attack_hb },
{ P_monsterinfo_currentmove, &boss2_move_attack_mg },
{ P_monsterinfo_currentmove, &boss2_move_attack_post_mg },
{ P_monsterinfo_currentmove, &boss2_move_attack_pre_mg },
{ P_monsterinfo_currentmove, &boss2_move_attack_rocket },
{ P_monsterinfo_currentmove, &boss2_move_attack_rocket2 },
{ P_monsterinfo_currentmove, &boss2_move_death },
{ P_monsterinfo_currentmove, &boss2_move_pain_heavy },
{ P_monsterinfo_currentmove, &boss2_move_pain_light },
{ P_monsterinfo_currentmove, &boss2_move_run },
{ P_monsterinfo_currentmove, &boss2_move_stand },
{ P_monsterinfo_currentmove, &boss2_move_walk },
{ P_monsterinfo_currentmove, &brain_move_attack1 },
{ P_monsterinfo_currentmove, &brain_move_attack2 },
{ P_monsterinfo_currentmove, &brain_move_attack3 },
{ P_monsterinfo_currentmove, &brain_move_attack4 },
{ P_monsterinfo_currentmove, &brain_move_death1 },
{ P_monsterinfo_currentmove, &brain_move_death2 },
{ P_monsterinfo_currentmove, &brain_move_duck },
{ P_monsterinfo_currentmove, &brain_move_idle },
{ P_monsterinfo_currentmove, &brain_move_pain1 },
{ P_monsterinfo_currentmove, &brain_move_pain2 },
{ P_monsterinfo_currentmove, &brain_move_pain3 },
{ P_monsterinfo_currentmove, &brain_move_run },
{ P_monsterinfo_currentmove, &brain_move_stand },
{ P_monsterinfo_currentmove, &brain_move_walk1 },
{ P_monsterinfo_currentmove, &carrier_move_attack_gren },
{ P_monsterinfo_currentmove, &carrier_move_attack_mg },
{ P_monsterinfo_currentmove, &carrier_move_attack_post_gren },
{ P_monsterinfo_currentmove, &carrier_move_attack_post_mg },
{ P_monsterinfo_currentmove, &carrier_move_attack_pre_gren },
{ P_monsterinfo_currentmove, &carrier_move_attack_pre_mg },
{ P_monsterinfo_currentmove, &carrier_move_attack_rail },
{ P_monsterinfo_currentmove, &carrier_move_attack_rocket },
{ P_monsterinfo_currentmove, &carrier_move_death },
{ P_monsterinfo_currentmove, &carrier_move_pain_heavy },
{ P_monsterinfo_currentmove, &carrier_move_pain_light },
{ P_monsterinfo_currentmove, &carrier_move_run },
{ P_monsterinfo_currentmove, &carrier_move_spawn },
{ P_monsterinfo_currentmove, &carrier_move_stand },
{ P_monsterinfo_currentmove, &carrier_move_walk },
{ P_monsterinfo_currentmove, &chick_move_attack1 },
{ P_monsterinfo_currentmove, &chick_move_death1 },
{ P_monsterinfo_currentmove, &chick_move_death2 },
{ P_monsterinfo_currentmove, &chick_move_duck },
{ P_monsterinfo_currentmove, &chick_move_end_attack1 },
{ P_monsterinfo_currentmove, &chick_move_end_slash },
{ P_monsterinfo_currentmove, &chick_move_fidget },
{ P_monsterinfo_currentmove, &chick_move_pain1 },
{ P_monsterinfo_currentmove, &chick_move_pain2 },
{ P_monsterinfo_currentmove, &chick_move_pain3 },
{ P_monsterinfo_currentmove, &chick_move_run },
{ P_monsterinfo_currentmove, &chick_move_slash },
{ P_monsterinfo_currentmove, &chick_move_stand },
{ P_monsterinfo_currentmove, &chick_move_start_attack1 },
{ P_monsterinfo_currentmove, &chick_move_start_run },
{ P_monsterinfo_currentmove, &chick_move_start_slash },
{ P_monsterinfo_currentmove, &chick_move_walk },
{ P_monsterinfo_currentmove, &flipper_move_attack },
{ P_monsterinfo_currentmove, &flipper_move_death },
{ P_monsterinfo_currentmove, &flipper_move_pain1 },
{ P_monsterinfo_currentmove, &flipper_move_pain2 },
{ P_monsterinfo_currentmove, &flipper_move_run_loop },
{ P_monsterinfo_currentmove, &flipper_move_run_start },
{ P_monsterinfo_currentmove, &flipper_move_stand },
{ P_monsterinfo_currentmove, &flipper_move_start_run },
{ P_monsterinfo_currentmove, &flipper_move_walk },
{ P_monsterinfo_currentmove, &floater_move_attack1 },
{ P_monsterinfo_currentmove, &floater_move_attack1a },
{ P_monsterinfo_currentmove, &floater_move_attack2 },
{ P_monsterinfo_currentmove, &floater_move_attack3 },
{ P_monsterinfo_currentmove, &floater_move_disguise },
{ P_monsterinfo_currentmove, &floater_move_pain1 },
{ P_monsterinfo_currentmove, &floater_move_pain2 },
{ P_monsterinfo_currentmove, &floater_move_pop },
{ P_monsterinfo_currentmove, &floater_move_run },
{ P_monsterinfo_currentmove, &floater_move_stand1 },
{ P_monsterinfo_currentmove, &floater_move_stand2 },
{ P_monsterinfo_currentmove, &floater_move_walk },
{ P_monsterinfo_currentmove, &flyer_move_attack2 },
{ P_monsterinfo_currentmove, &flyer_move_attack3 },
{ P_monsterinfo_currentmove, &flyer_move_end_melee },
{ P_monsterinfo_currentmove, &flyer_move_kamikaze },
{ P_monsterinfo_currentmove, &flyer_move_loop_melee },
{ P_monsterinfo_currentmove, &flyer_move_pain1 },
{ P_monsterinfo_currentmove, &flyer_move_pain2 },
{ P_monsterinfo_currentmove, &flyer_move_pain3 },
{ P_monsterinfo_currentmove, &flyer_move_run },
{ P_monsterinfo_currentmove, &flyer_move_stand },
{ P_monsterinfo_currentmove, &flyer_move_start },
{ P_monsterinfo_currentmove, &flyer_move_start_melee },
{ P_monsterinfo_currentmove, &flyer_move_stop },
{ P_monsterinfo_currentmove, &flyer_move_walk },
{ P_monsterinfo_currentmove, &gekk_move_attack },
{ P_monsterinfo_currentmove, &gekk_move_attack1 },
{ P_monsterinfo_currentmove, &gekk_move_attack2 },
{ P_monsterinfo_currentmove, &gekk_move_chant },
{ P_monsterinfo_currentmove, &gekk_move_death1 },
{ P_monsterinfo_currentmove, &gekk_move_death3 },
{ P_monsterinfo_currentmove, &gekk_move_death4 },
{ P_monsterinfo_currentmove, &gekk_move_idle },
{ P_monsterinfo_currentmove, &gekk_move_idle2 },
{ P_monsterinfo_currentmove, &gekk_move_lduck },
{ P_monsterinfo_currentmove, &gekk_move_leapatk },
{ P_monsterinfo_currentmove, &gekk_move_leapatk2 },
{ P_monsterinfo_currentmove, &gekk_move_pain },
{ P_monsterinfo_currentmove, &gekk_move_pain1 },
{ P_monsterinfo_currentmove, &gekk_move_pain2 },
{ P_monsterinfo_currentmove, &gekk_move_rduck },
{ P_monsterinfo_currentmove, &gekk_move_run },
{ P_monsterinfo_currentmove, &gekk_move_run_start },
{ P_monsterinfo_currentmove, &gekk_move_spit },
{ P_monsterinfo_currentmove, &gekk_move_stand },
{ P_monsterinfo_currentmove, &gekk_move_standunderwater },
{ P_monsterinfo_currentmove, &gekk_move_swim_loop },
{ P_monsterinfo_currentmove, &gekk_move_swim_start },
{ P_monsterinfo_currentmove, &gekk_move_walk },
{ P_monsterinfo_currentmove, &gekk_move_wdeath },
{ P_monsterinfo_currentmove, &gladb_move_attack_gun },
{ P_monsterinfo_currentmove, &gladiator_move_attack_gun },
{ P_monsterinfo_currentmove, &gladiator_move_attack_melee },
{ P_monsterinfo_currentmove, &gladiator_move_death },
{ P_monsterinfo_currentmove, &gladiator_move_pain },
{ P_monsterinfo_currentmove, &gladiator_move_pain_air },
{ P_monsterinfo_currentmove, &gladiator_move_run },
{ P_monsterinfo_currentmove, &gladiator_move_stand },
{ P_monsterinfo_currentmove, &gladiator_move_walk },
{ P_monsterinfo_currentmove, &guncmdr_move_attack_chain },
{ P_monsterinfo_currentmove, &guncmdr_move_attack_grenade_back },
{ P_monsterinfo_currentmove, &guncmdr_move_attack_grenade_back_dodge_left },
{ P_monsterinfo_currentmove, &guncmdr_move_attack_grenade_back_dodge_right },
{ P_monsterinfo_currentmove, &guncmdr_move_attack_kick },
{ P_monsterinfo_currentmove, &guncmdr_move_attack_mortar },
{ P_monsterinfo_currentmove, &guncmdr_move_attack_mortar_dodge },
{ P_monsterinfo_currentmove, &guncmdr_move_death1 },
{ P_monsterinfo_currentmove, &guncmdr_move_death2 },
{ P_monsterinfo_currentmove, &guncmdr_move_death3 },
{ P_monsterinfo_currentmove, &guncmdr_move_death4 },
{ P_monsterinfo_currentmove, &guncmdr_move_death5 },
{ P_monsterinfo_currentmove, &guncmdr_move_death6 },
{ P_monsterinfo_currentmove, &guncmdr_move_death7 },
{ P_monsterinfo_currentmove, &guncmdr_move_duck_attack },
{ P_monsterinfo_currentmove, &guncmdr_move_endfire_chain },
{ P_monsterinfo_currentmove, &guncmdr_move_fidget },
{ P_monsterinfo_currentmove, &guncmdr_move_fire_chain },
{ P_monsterinfo_currentmove, &guncmdr_move_fire_chain_dodge_left },
{ P_monsterinfo_currentmove, &guncmdr_move_fire_chain_dodge_right },
{ P_monsterinfo_currentmove, &guncmdr_move_fire_chain_run },
{ P_monsterinfo_currentmove, &guncmdr_move_jump },
{ P_monsterinfo_currentmove, &guncmdr_move_jump2 },
{ P_monsterinfo_currentmove, &guncmdr_move_pain1 },
{ P_monsterinfo_currentmove, &guncmdr_move_pain2 },
{ P_monsterinfo_currentmove, &guncmdr_move_pain3 },
{ P_monsterinfo_currentmove, &guncmdr_move_pain4 },
{ P_monsterinfo_currentmove, &guncmdr_move_pain5 },
{ P_monsterinfo_currentmove, &guncmdr_move_pain6 },
{ P_monsterinfo_currentmove, &guncmdr_move_pain7 },
{ P_monsterinfo_currentmove, &guncmdr_move_run },
{ P_monsterinfo_currentmove, &guncmdr_move_stand },
{ P_monsterinfo_currentmove, &guncmdr_move_walk },
{ P_monsterinfo_currentmove, &gunner_move_attack_chain },
{ P_monsterinfo_currentmove, &gunner_move_attack_grenade },
{ P_monsterinfo_currentmove, &gunner_move_attack_grenade2 },
{ P_monsterinfo_currentmove, &gunner_move_death },
{ P_monsterinfo_currentmove, &gunner_move_duck },
{ P_monsterinfo_currentmove, &gunner_move_endfire_chain },
{ P_monsterinfo_currentmove, &gunner_move_fidget },
{ P_monsterinfo_currentmove, &gunner_move_fire_chain },
{ P_monsterinfo_currentmove, &gunner_move_jump },
{ P_monsterinfo_currentmove, &gunner_move_jump2 },
{ P_monsterinfo_currentmove, &gunner_move_pain1 },
{ P_monsterinfo_currentmove, &gunner_move_pain2 },
{ P_monsterinfo_currentmove, &gunner_move_pain3 },
{ P_monsterinfo_currentmove, &gunner_move_run },
{ P_monsterinfo_currentmove, &gunner_move_runandshoot },
{ P_monsterinfo_currentmove, &gunner_move_stand },
{ P_monsterinfo_currentmove, &gunner_move_walk },
{ P_monsterinfo_currentmove, &hover_move_attack1 },
{ P_monsterinfo_currentmove, &hover_move_attack2 },
{ P_monsterinfo_currentmove, &hover_move_death1 },
{ P_monsterinfo_currentmove, &hover_move_end_attack },
{ P_monsterinfo_currentmove, &hover_move_pain1 },
{ P_monsterinfo_currentmove, &hover_move_pain2 },
{ P_monsterinfo_currentmove, &hover_move_pain3 },
{ P_monsterinfo_currentmove, &hover_move_run },
{ P_monsterinfo_currentmove, &hover_move_stand },
{ P_monsterinfo_currentmove, &hover_move_start_attack },
{ P_monsterinfo_currentmove, &hover_move_walk },
{ P_monsterinfo_currentmove, &infantry_move_attack1 },
{ P_monsterinfo_currentmove, &infantry_move_attack1_classic },
{ P_monsterinfo_currentmove, &infantry_move_attack2 },
{ P_monsterinfo_currentmove, &infantry_move_attack3 },
{ P_monsterinfo_currentmove, &infantry_move_attack4 },
{ P_monsterinfo_currentmove, &infantry_move_attack5 },
{ P_monsterinfo_currentmove, &infantry_move_death1 },
{ P_monsterinfo_currentmove, &infantry_move_death2 },
{ P_monsterinfo_currentmove, &infantry_move_death3 },
{ P_monsterinfo_currentmove, &infantry_move_duck },
{ P_monsterinfo_currentmove, &infantry_move_fidget },
{ P_monsterinfo_currentmove, &infantry_move_jump },
{ P_monsterinfo_currentmove, &infantry_move_jump2 },
{ P_monsterinfo_currentmove, &infantry_move_pain1 },
{ P_monsterinfo_currentmove, &infantry_move_pain2 },
{ P_monsterinfo_currentmove, &infantry_move_run },
{ P_monsterinfo_currentmove, &infantry_move_stand },
{ P_monsterinfo_currentmove, &infantry_move_walk },
{ P_monsterinfo_currentmove, &insane_move_crawl },
{ P_monsterinfo_currentmove, &insane_move_crawl_death },
{ P_monsterinfo_currentmove, &insane_move_crawl_pain },
{ P_monsterinfo_currentmove, &insane_move_cross },
{ P_monsterinfo_currentmove, &insane_move_down },
{ P_monsterinfo_currentmove, &insane_move_downtoup },
{ P_monsterinfo_currentmove, &insane_move_jumpdown },
{ P_monsterinfo_currentmove, &insane_move_run_insane },
{ P_monsterinfo_currentmove, &insane_move_run_normal },
{ P_monsterinfo_currentmove, &insane_move_runcrawl },
{ P_monsterinfo_currentmove, &insane_move_stand_death },
{ P_monsterinfo_currentmove, &insane_move_stand_insane },
{ P_monsterinfo_currentmove, &insane_move_stand_normal },
{ P_monsterinfo_currentmove, &insane_move_stand_pain },
{ P_monsterinfo_currentmove, &insane_move_struggle_cross },
{ P_monsterinfo_currentmove, &insane_move_uptodown },
{ P_monsterinfo_currentmove, &insane_move_walk_insane },
{ P_monsterinfo_currentmove, &insane_move_walk_normal },
{ P_monsterinfo_currentmove, &jorg_move_attack1 },
{ P_monsterinfo_currentmove, &jorg_move_attack2 },
{ P_monsterinfo_currentmove, &jorg_move_death },
{ P_monsterinfo_currentmove, &jorg_move_end_attack1 },
{ P_monsterinfo_currentmove, &jorg_move_pain1 },
{ P_monsterinfo_currentmove, &jorg_move_pain2 },
{ P_monsterinfo_currentmove, &jorg_move_pain3 },
{ P_monsterinfo_currentmove, &jorg_move_run },
{ P_monsterinfo_currentmove, &jorg_move_stand },
{ P_monsterinfo_currentmove, &jorg_move_start_attack1 },
{ P_monsterinfo_currentmove, &jorg_move_walk },
{ P_monsterinfo_currentmove, &makron_move_attack3 },
{ P_monsterinfo_currentmove, &makron_move_attack4 },
{ P_monsterinfo_currentmove, &makron_move_attack5 },
{ P_monsterinfo_currentmove, &makron_move_death2 },
{ P_monsterinfo_currentmove, &makron_move_pain4 },
{ P_monsterinfo_currentmove, &makron_move_pain5 },
{ P_monsterinfo_currentmove, &makron_move_pain6 },
{ P_monsterinfo_currentmove, &makron_move_run },
{ P_monsterinfo_currentmove, &makron_move_sight },
{ P_monsterinfo_currentmove, &makron_move_stand },
{ P_monsterinfo_currentmove, &makron_move_walk },
{ P_monsterinfo_currentmove, &medic_move_attackBlaster },
{ P_monsterinfo_currentmove, &medic_move_attackCable },
{ P_monsterinfo_currentmove, &medic_move_attackHyperBlaster },
{ P_monsterinfo_currentmove, &medic_move_callReinforcements },
{ P_monsterinfo_currentmove, &medic_move_death },
{ P_monsterinfo_currentmove, &medic_move_duck },
{ P_monsterinfo_currentmove, &medic_move_pain1 },
{ P_monsterinfo_currentmove, &medic_move_pain2 },
{ P_monsterinfo_currentmove, &medic_move_run },
{ P_monsterinfo_currentmove, &medic_move_stand },
{ P_monsterinfo_currentmove, &medic_move_walk },
{ P_monsterinfo_currentmove, &mutant_move_attack },
{ P_monsterinfo_currentmove, &mutant_move_death1 },
{ P_monsterinfo_currentmove, &mutant_move_death2 },
{ P_monsterinfo_currentmove, &mutant_move_idle },
{ P_monsterinfo_currentmove, &mutant_move_jump },
{ P_monsterinfo_currentmove, &mutant_move_jump_down },
{ P_monsterinfo_currentmove, &mutant_move_jump_up },
{ P_monsterinfo_currentmove, &mutant_move_pain1 },
{ P_monsterinfo_currentmove, &mutant_move_pain2 },
{ P_monsterinfo_currentmove, &mutant_move_pain3 },
{ P_monsterinfo_currentmove, &mutant_move_run },
{ P_monsterinfo_currentmove, &mutant_move_stand },
{ P_monsterinfo_currentmove, &mutant_move_start_walk },
{ P_monsterinfo_currentmove, &mutant_move_walk },
{ P_monsterinfo_currentmove, &parasite_move_break },
{ P_monsterinfo_currentmove, &parasite_move_death },
{ P_monsterinfo_currentmove, &parasite_move_drain },
{ P_monsterinfo_currentmove, &parasite_move_end_fidget },
{ P_monsterinfo_currentmove, &parasite_move_fidget },
{ P_monsterinfo_currentmove, &parasite_move_fire_proboscis },
{ P_monsterinfo_currentmove, &parasite_move_jump_down },
{ P_monsterinfo_currentmove, &parasite_move_jump_up },
{ P_monsterinfo_currentmove, &parasite_move_pain1 },
{ P_monsterinfo_currentmove, &parasite_move_run },
{ P_monsterinfo_currentmove, &parasite_move_stand },
{ P_monsterinfo_currentmove, &parasite_move_start_fidget },
{ P_monsterinfo_currentmove, &parasite_move_start_run },
{ P_monsterinfo_currentmove, &parasite_move_start_walk },
{ P_monsterinfo_currentmove, &parasite_move_walk },
{ P_monsterinfo_currentmove, &shambler_attack_magic },
{ P_monsterinfo_currentmove, &shambler_attack_smash },
{ P_monsterinfo_currentmove, &shambler_attack_swingl },
{ P_monsterinfo_currentmove, &shambler_attack_swingr },
{ P_monsterinfo_currentmove, &shambler_move_death },
{ P_monsterinfo_currentmove, &shambler_move_pain },
{ P_monsterinfo_currentmove, &shambler_move_run },
{ P_monsterinfo_currentmove, &shambler_move_stand },
{ P_monsterinfo_currentmove, &shambler_move_walk },
{ P_monsterinfo_currentmove, &soldier_move_attack1 },
{ P_monsterinfo_currentmove, &soldier_move_attack2 },
{ P_monsterinfo_currentmove, &soldier_move_attack3 },
{ P_monsterinfo_currentmove, &soldier_move_attack4 },
{ P_monsterinfo_currentmove, &soldier_move_attack5 },
{ P_monsterinfo_currentmove, &soldier_move_attack6 },
{ P_monsterinfo_currentmove, &soldier_move_blind },
{ P_monsterinfo_currentmove, &soldier_move_death1 },
{ P_monsterinfo_currentmove, &soldier_move_death2 },
{ P_monsterinfo_currentmove, &soldier_move_death3 },
{ P_monsterinfo_currentmove, &soldier_move_death4 },
{ P_monsterinfo_currentmove, &soldier_move_death5 },
{ P_monsterinfo_currentmove, &soldier_move_death6 },
{ P_monsterinfo_currentmove, &soldier_move_duck },
{ P_monsterinfo_currentmove, &soldier_move_pain1 },
{ P_monsterinfo_currentmove, &soldier_move_pain2 },
{ P_monsterinfo_currentmove, &soldier_move_pain3 },
{ P_monsterinfo_currentmove, &soldier_move_pain4 },
{ P_monsterinfo_currentmove, &soldier_move_run },
{ P_monsterinfo_currentmove, &soldier_move_stand1 },
{ P_monsterinfo_currentmove, &soldier_move_stand2 },
{ P_monsterinfo_currentmove, &soldier_move_stand3 },
{ P_monsterinfo_currentmove, &soldier_move_start_run },
{ P_monsterinfo_currentmove, &soldier_move_trip },
{ P_monsterinfo_currentmove, &soldier_move_walk1 },
{ P_monsterinfo_currentmove, &soldier_move_walk2 },
{ P_monsterinfo_currentmove, &soldierh_move_attack1 },
{ P_monsterinfo_currentmove, &soldierh_move_attack2 },
{ P_monsterinfo_currentmove, &stalker_move_death },
{ P_monsterinfo_currentmove, &stalker_move_false_death },
{ P_monsterinfo_currentmove, &stalker_move_false_death_end },
{ P_monsterinfo_currentmove, &stalker_move_false_death_start },
{ P_monsterinfo_currentmove, &stalker_move_idle },
{ P_monsterinfo_currentmove, &stalker_move_idle2 },
{ P_monsterinfo_currentmove, &stalker_move_jump_down },
{ P_monsterinfo_currentmove, &stalker_move_jump_straightup },
{ P_monsterinfo_currentmove, &stalker_move_jump_up },
{ P_monsterinfo_currentmove, &stalker_move_pain },
{ P_monsterinfo_currentmove, &stalker_move_run },
{ P_monsterinfo_currentmove, &stalker_move_shoot },
{ P_monsterinfo_currentmove, &stalker_move_stand },
{ P_monsterinfo_currentmove, &stalker_move_swing_l },
{ P_monsterinfo_currentmove, &stalker_move_swing_r },
{ P_monsterinfo_currentmove, &stalker_move_walk },
{ P_monsterinfo_currentmove, &supertank_move_attack1 },
{ P_monsterinfo_currentmove, &supertank_move_attack2 },
{ P_monsterinfo_currentmove, &supertank_move_death },
{ P_monsterinfo_currentmove, &supertank_move_end_attack1 },
{ P_monsterinfo_currentmove, &supertank_move_forward },
{ P_monsterinfo_currentmove, &supertank_move_pain1 },
{ P_monsterinfo_currentmove, &supertank_move_pain2 },
{ P_monsterinfo_currentmove, &supertank_move_pain3 },
{ P_monsterinfo_currentmove, &supertank_move_run },
{ P_monsterinfo_currentmove, &supertank_move_stand },
{ P_monsterinfo_currentmove, &tank_move_attack_blast },
{ P_monsterinfo_currentmove, &tank_move_attack_chain },
{ P_monsterinfo_currentmove, &tank_move_attack_fire_rocket },
{ P_monsterinfo_currentmove, &tank_move_attack_post_blast },
{ P_monsterinfo_currentmove, &tank_move_attack_post_rocket },
{ P_monsterinfo_currentmove, &tank_move_attack_pre_rocket },
{ P_monsterinfo_currentmove, &tank_move_attack_strike },
{ P_monsterinfo_currentmove, &tank_move_death },
{ P_monsterinfo_currentmove, &tank_move_pain1 },
{ P_monsterinfo_currentmove, &tank_move_pain2 },
{ P_monsterinfo_currentmove, &tank_move_pain3 },
{ P_monsterinfo_currentmove, &tank_move_reattack_blast },
{ P_monsterinfo_currentmove, &tank_move_run },
{ P_monsterinfo_currentmove, &tank_move_stand },
{ P_monsterinfo_currentmove, &tank_move_start_run },
{ P_monsterinfo_currentmove, &tank_move_walk },
{ P_monsterinfo_currentmove, &turret_move_fire },
{ P_monsterinfo_currentmove, &turret_move_ready_gun },
{ P_monsterinfo_currentmove, &turret_move_run },
{ P_monsterinfo_currentmove, &turret_move_seek },
{ P_monsterinfo_currentmove, &turret_move_stand },
{ P_monsterinfo_stand, actor_stand },
{ P_monsterinfo_stand, arachnid_stand },
{ P_monsterinfo_stand, berserk_stand },
{ P_monsterinfo_stand, boss2_stand },
{ P_monsterinfo_stand, brain_stand },
{ P_monsterinfo_stand, carrier_stand },
{ P_monsterinfo_stand, chick_stand },
{ P_monsterinfo_stand, flipper_stand },
{ P_monsterinfo_stand, floater_stand },
{ P_monsterinfo_stand, flyer_stand },
{ P_monsterinfo_stand, gekk_stand },
{ P_monsterinfo_stand, gladiator_stand },
{ P_monsterinfo_stand, guncmdr_stand },
{ P_monsterinfo_stand, gunner_stand },
{ P_monsterinfo_stand, hover_stand },
{ P_monsterinfo_stand, infantry_stand },
{ P_monsterinfo_stand, insane_stand },
{ P_monsterinfo_stand, jorg_stand },
{ P_monsterinfo_stand, makron_stand },
{ P_monsterinfo_stand, medic_stand },
{ P_monsterinfo_stand, mutant_stand },
{ P_monsterinfo_stand, parasite_stand },
{ P_monsterinfo_stand, shambler_stand },
{ P_monsterinfo_stand, soldier_blind },
{ P_monsterinfo_stand, soldier_stand },
{ P_monsterinfo_stand, stalker_stand },
{ P_monsterinfo_stand, supertank_stand },
{ P_monsterinfo_stand, tank_stand },
{ P_monsterinfo_stand, turret_stand },
{ P_monsterinfo_idle, brain_idle },
{ P_monsterinfo_idle, floater_idle },
{ P_monsterinfo_idle, flyer_idle },
{ P_monsterinfo_idle, gekk_idle },
{ P_monsterinfo_idle, gladiator_idle },
{ P_monsterinfo_idle, infantry_fidget },
{ P_monsterinfo_idle, medic_idle },
{ P_monsterinfo_idle, mutant_idle },
{ P_monsterinfo_idle, parasite_idle },
{ P_monsterinfo_idle, shambler_idle },
{ P_monsterinfo_idle, stalker_idle },
{ P_monsterinfo_idle, tank_idle },
{ P_monsterinfo_search, berserk_search },
{ P_monsterinfo_search, boss2_search },
{ P_monsterinfo_search, brain_search },
{ P_monsterinfo_search, gekk_search },
{ P_monsterinfo_search, gladiator_search },
{ P_monsterinfo_search, guncmdr_search },
{ P_monsterinfo_search, gunner_search },
{ P_monsterinfo_search, hover_search },
{ P_monsterinfo_search, jorg_search },
{ P_monsterinfo_search, medic_search },
{ P_monsterinfo_search, mutant_search },
{ P_monsterinfo_search, supertank_search },
{ P_monsterinfo_search, turret_search },
{ P_monsterinfo_walk, actor_walk },
{ P_monsterinfo_walk, arachnid_walk },
{ P_monsterinfo_walk, berserk_walk },
{ P_monsterinfo_walk, boss2_walk },
{ P_monsterinfo_walk, brain_walk },
{ P_monsterinfo_walk, carrier_walk },
{ P_monsterinfo_walk, chick_walk },
{ P_monsterinfo_walk, flipper_walk },
{ P_monsterinfo_walk, floater_walk },
{ P_monsterinfo_walk, flyer_walk },
{ P_monsterinfo_walk, gekk_walk },
{ P_monsterinfo_walk, gladiator_walk },
{ P_monsterinfo_walk, guncmdr_walk },
{ P_monsterinfo_walk, gunner_walk },
{ P_monsterinfo_walk, hover_walk },
{ P_monsterinfo_walk, infantry_walk },
{ P_monsterinfo_walk, insane_walk },
{ P_monsterinfo_walk, jorg_walk },
{ P_monsterinfo_walk, makron_walk },
{ P_monsterinfo_walk, medic_walk },
{ P_monsterinfo_walk, mutant_walk },
{ P_monsterinfo_walk, parasite_start_walk },
{ P_monsterinfo_walk, shambler_walk },
{ P_monsterinfo_walk, soldier_walk },
{ P_monsterinfo_walk, stalker_walk },
{ P_monsterinfo_walk, supertank_walk },
{ P_monsterinfo_walk, tank_walk },
{ P_monsterinfo_walk, turret_walk },
{ P_monsterinfo_run, actor_run },
{ P_monsterinfo_run, arachnid_run },
{ P_monsterinfo_run, berserk_run },
{ P_monsterinfo_run, boss2_run },
{ P_monsterinfo_run, brain_run },
{ P_monsterinfo_run, carrier_run },
{ P_monsterinfo_run, chick_run },
{ P_monsterinfo_run, flipper_start_run },
{ P_monsterinfo_run, floater_run },
{ P_monsterinfo_run, flyer_run },
{ P_monsterinfo_run, gekk_run_start },
{ P_monsterinfo_run, gladiator_run },
{ P_monsterinfo_run, guncmdr_run },
{ P_monsterinfo_run, gunner_run },
{ P_monsterinfo_run, hover_run },
{ P_monsterinfo_run, infantry_run },
{ P_monsterinfo_run, insane_run },
{ P_monsterinfo_run, jorg_run },
{ P_monsterinfo_run, makron_run },
{ P_monsterinfo_run, medic_run },
{ P_monsterinfo_run, mutant_run },
{ P_monsterinfo_run, parasite_start_run },
{ P_monsterinfo_run, shambler_run },
{ P_monsterinfo_run, soldier_run },
{ P_monsterinfo_run, stalker_run },
{ P_monsterinfo_run, supertank_run },
{ P_monsterinfo_run, tank_run },
{ P_monsterinfo_run, turret_run },
{ P_monsterinfo_dodge, gekk_dodge },
{ P_monsterinfo_dodge, M_MonsterDodge },
{ P_monsterinfo_dodge, stalker_dodge },
{ P_monsterinfo_attack, actor_attack },
{ P_monsterinfo_attack, arachnid_attack },
{ P_monsterinfo_attack, berserk_attack },
{ P_monsterinfo_attack, boss2_attack },
{ P_monsterinfo_attack, brain_attack },
{ P_monsterinfo_attack, carrier_attack },
{ P_monsterinfo_attack, chick_attack },
{ P_monsterinfo_attack, floater_attack },
{ P_monsterinfo_attack, flyer_attack },
{ P_monsterinfo_attack, gekk_attack },
{ P_monsterinfo_attack, gladiator_attack },
{ P_monsterinfo_attack, guncmdr_attack },
{ P_monsterinfo_attack, gunner_attack },
{ P_monsterinfo_attack, hover_start_attack },
{ P_monsterinfo_attack, infantry_attack },
{ P_monsterinfo_attack, jorg_attack },
{ P_monsterinfo_attack, makron_attack },
{ P_monsterinfo_attack, medic_attack },
{ P_monsterinfo_attack, mutant_jump },
{ P_monsterinfo_attack, parasite_attack },
{ P_monsterinfo_attack, shambler_attack },
{ P_monsterinfo_attack, soldier_attack },
{ P_monsterinfo_attack, stalker_attack_ranged },
{ P_monsterinfo_attack, supertank_attack },
{ P_monsterinfo_attack, tank_attack },
{ P_monsterinfo_attack, turret_attack },
{ P_monsterinfo_melee, berserk_melee },
{ P_monsterinfo_melee, brain_melee },
{ P_monsterinfo_melee, chick_melee },
{ P_monsterinfo_melee, flipper_melee },
{ P_monsterinfo_melee, floater_melee },
{ P_monsterinfo_melee, flyer_melee },
{ P_monsterinfo_melee, gekk_melee },
{ P_monsterinfo_melee, gladiator_melee },
{ P_monsterinfo_melee, mutant_melee },
{ P_monsterinfo_melee, shambler_melee },
{ P_monsterinfo_melee, stalker_attack_melee },
{ P_monsterinfo_sight, arachnid_sight },
{ P_monsterinfo_sight, berserk_sight },
{ P_monsterinfo_sight, brain_sight },
{ P_monsterinfo_sight, carrier_sight },
{ P_monsterinfo_sight, chick_sight },
{ P_monsterinfo_sight, flipper_sight },
{ P_monsterinfo_sight, floater_sight },
{ P_monsterinfo_sight, flyer_sight },
{ P_monsterinfo_sight, gekk_sight },
{ P_monsterinfo_sight, gladiator_sight },
{ P_monsterinfo_sight, guncmdr_sight },
{ P_monsterinfo_sight, gunner_sight },
{ P_monsterinfo_sight, hover_sight },
{ P_monsterinfo_sight, infantry_sight },
{ P_monsterinfo_sight, makron_sight },
{ P_monsterinfo_sight, medic_sight },
{ P_monsterinfo_sight, mutant_sight },
{ P_monsterinfo_sight, parasite_sight },
{ P_monsterinfo_sight, shambler_sight },
{ P_monsterinfo_sight, soldier_sight },
{ P_monsterinfo_sight, stalker_sight },
{ P_monsterinfo_sight, tank_sight },
{ P_monsterinfo_sight, turret_sight },
{ P_monsterinfo_checkattack, Boss2_CheckAttack },
{ P_monsterinfo_checkattack, Carrier_CheckAttack },
{ P_monsterinfo_checkattack, gekk_checkattack },
{ P_monsterinfo_checkattack, Jorg_CheckAttack },
{ P_monsterinfo_checkattack, M_CheckAttack },
{ P_monsterinfo_checkattack, Makron_CheckAttack },
{ P_monsterinfo_checkattack, medic_checkattack },
{ P_monsterinfo_checkattack, mutant_checkattack },
{ P_monsterinfo_checkattack, turret_checkattack },
{ P_monsterinfo_blocked, berserk_blocked },
{ P_monsterinfo_blocked, guncmdr_blocked },
{ P_monsterinfo_blocked, gunner_blocked },
{ P_monsterinfo_blocked, infantry_blocked },
{ P_monsterinfo_blocked, mutant_blocked },
{ P_monsterinfo_blocked, parasite_blocked },
};
const int num_save_ptrs = sizeof(save_ptrs) / sizeof(save_ptrs[0]);
