/*
Copyright (c) ZeniMax Media Inc.
Licensed under the GNU General Public License 2.0.
*/
// Generated from src/rerelease/m_arachnid.h. The arachnid has its own model,
// so these frames are self-contained.

#define FRAME_rails1             0
#define FRAME_rails2             1
#define FRAME_rails3             2
#define FRAME_rails4             3
#define FRAME_rails5             4
#define FRAME_rails6             5
#define FRAME_rails7             6
#define FRAME_rails8             7
#define FRAME_rails9             8
#define FRAME_rails10            9
#define FRAME_rails11            10
#define FRAME_death1             11
#define FRAME_death2             12
#define FRAME_death3             13
#define FRAME_death4             14
#define FRAME_death5             15
#define FRAME_death6             16
#define FRAME_death7             17
#define FRAME_death8             18
#define FRAME_death9             19
#define FRAME_death10            20
#define FRAME_death11            21
#define FRAME_death12            22
#define FRAME_death13            23
#define FRAME_death14            24
#define FRAME_death15            25
#define FRAME_death16            26
#define FRAME_death17            27
#define FRAME_death18            28
#define FRAME_death19            29
#define FRAME_death20            30
#define FRAME_melee_atk1         31
#define FRAME_melee_atk2         32
#define FRAME_melee_atk3         33
#define FRAME_melee_atk4         34
#define FRAME_melee_atk5         35
#define FRAME_melee_atk6         36
#define FRAME_melee_atk7         37
#define FRAME_melee_atk8         38
#define FRAME_melee_atk9         39
#define FRAME_melee_atk10        40
#define FRAME_melee_atk11        41
#define FRAME_melee_atk12        42
#define FRAME_pain11             43
#define FRAME_pain12             44
#define FRAME_pain13             45
#define FRAME_pain14             46
#define FRAME_pain15             47
#define FRAME_idle1              48
#define FRAME_idle2              49
#define FRAME_idle3              50
#define FRAME_idle4              51
#define FRAME_idle5              52
#define FRAME_idle6              53
#define FRAME_idle7              54
#define FRAME_idle8              55
#define FRAME_idle9              56
#define FRAME_idle10             57
#define FRAME_idle11             58
#define FRAME_idle12             59
#define FRAME_idle13             60
#define FRAME_walk1              61
#define FRAME_walk2              62
#define FRAME_walk3              63
#define FRAME_walk4              64
#define FRAME_walk5              65
#define FRAME_walk6              66
#define FRAME_walk7              67
#define FRAME_walk8              68
#define FRAME_walk9              69
#define FRAME_walk10             70
#define FRAME_turn1              71
#define FRAME_turn2              72
#define FRAME_turn3              73
#define FRAME_melee_out1         74
#define FRAME_melee_out2         75
#define FRAME_melee_out3         76
#define FRAME_pain21             77
#define FRAME_pain22             78
#define FRAME_pain23             79
#define FRAME_pain24             80
#define FRAME_pain25             81
#define FRAME_pain26             82
#define FRAME_melee_pain1        83
#define FRAME_melee_pain2        84
#define FRAME_melee_pain3        85
#define FRAME_melee_pain4        86
#define FRAME_melee_pain5        87
#define FRAME_melee_pain6        88
#define FRAME_melee_pain7        89
#define FRAME_melee_pain8        90
#define FRAME_melee_pain9        91
#define FRAME_melee_pain10       92
#define FRAME_melee_pain11       93
#define FRAME_melee_pain12       94
#define FRAME_melee_pain13       95
#define FRAME_melee_pain14       96
#define FRAME_melee_pain15       97
#define FRAME_melee_pain16       98
#define FRAME_melee_in1          99
#define FRAME_melee_in2          100
#define FRAME_melee_in3          101
#define FRAME_melee_in4          102
#define FRAME_melee_in5          103
#define FRAME_melee_in6          104
#define FRAME_melee_in7          105
#define FRAME_melee_in8          106
#define FRAME_melee_in9          107
#define FRAME_melee_in10         108
#define FRAME_melee_in11         109
#define FRAME_melee_in12         110
#define FRAME_melee_in13         111
#define FRAME_melee_in14         112
#define FRAME_melee_in15         113
#define FRAME_melee_in16         114
#define FRAME_rails_up1          115
#define FRAME_rails_up2          116
#define FRAME_rails_up3          117
#define FRAME_rails_up4          118
#define FRAME_rails_up5          119
#define FRAME_rails_up6          120
#define FRAME_rails_up7          121
#define FRAME_rails_up8          122
#define FRAME_rails_up9          123
#define FRAME_rails_up10         124
#define FRAME_rails_up11         125
#define FRAME_rails_up12         126
#define FRAME_rails_up13         127
#define FRAME_rails_up14         128
#define FRAME_rails_up15         129
#define FRAME_rails_up16         130

#define MODEL_SCALE     1.000000
