# Writes mod_version.h with the Overdrive release version, branch and commit.
#
# Run with "cmake -P" from a build-time custom target, not at configure time:
# an execute_process() in CMakeLists.txt only runs when the project is
# configured, so an IDE that just rebuilds kept stamping the exe with the
# commit it was configured at (the console said cc0534ac on a build of
# 9013b7d8). The header is only rewritten when its contents change, so a
# build at the same commit recompiles nothing.
#
# Inputs: GIT_EXECUTABLE, SOURCE_DIR, OUTPUT_FILE

# The version is the nearest v* tag behind HEAD ("v1.0.4" -> "1.0.4"). The
# Overdrive tags sit in front of NVIDIA's upstream ones (v1.7.0, v1.8.1), so
# those are only reached if the Overdrive tags are missing.
execute_process(
	COMMAND "${GIT_EXECUTABLE}" describe --tags --match "v[0-9]*" --abbrev=0
	WORKING_DIRECTORY "${SOURCE_DIR}"
	OUTPUT_VARIABLE MOD_TAG
	OUTPUT_STRIP_TRAILING_WHITESPACE
	ERROR_QUIET
)
string(REGEX REPLACE "^v" "" MOD_VERSION "${MOD_TAG}")
if(NOT MOD_VERSION)
	# A shallow CI checkout has no tags
	set(MOD_VERSION "dev")
endif()

execute_process(
	COMMAND "${GIT_EXECUTABLE}" rev-parse --short=8 HEAD
	WORKING_DIRECTORY "${SOURCE_DIR}"
	OUTPUT_VARIABLE MOD_SHA
	OUTPUT_STRIP_TRAILING_WHITESPACE
	ERROR_QUIET
)
if(NOT MOD_SHA)
	set(MOD_SHA "unknown")
endif()

execute_process(
	COMMAND "${GIT_EXECUTABLE}" rev-parse --abbrev-ref HEAD
	WORKING_DIRECTORY "${SOURCE_DIR}"
	OUTPUT_VARIABLE MOD_BRANCH
	OUTPUT_STRIP_TRAILING_WHITESPACE
	ERROR_QUIET
)
# Actions checks out a detached HEAD; it names the branch in the environment
if((NOT MOD_BRANCH OR MOD_BRANCH STREQUAL "HEAD") AND DEFINED ENV{GITHUB_REF_NAME})
	set(MOD_BRANCH "$ENV{GITHUB_REF_NAME}")
endif()
if(NOT MOD_BRANCH)
	set(MOD_BRANCH "unknown")
endif()

set(CONTENT "// Generated by cmake/mod_version.cmake on every build - do not edit\n")
string(APPEND CONTENT "#define MOD_VERSION_STRING \"${MOD_VERSION}\"\n")
string(APPEND CONTENT "#define MOD_LONG_VERSION_STRING \"${MOD_VERSION}-${MOD_BRANCH}-${MOD_SHA}\"\n")

file(WRITE "${OUTPUT_FILE}.tmp" "${CONTENT}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUTPUT_FILE}.tmp" "${OUTPUT_FILE}")
file(REMOVE "${OUTPUT_FILE}.tmp")
